### ISSUE TITLE
AssertionError: Conflict of field 'guidance' and 'guidance_end'

### ISSUE THREAD

**Issue by knuthnads** [ub-gains/gains#2]
No longer seems to be functional. Clicking on 'Generate' in Entity Painter produces an assertion error.

Error in Unity:

```
UnityEngine.Debug:LogError (object)
UntoldByte.GAINS.Editor.StableDiffusionModule/<MakeRequest>d__187:MoveNext () (at Assets/UntoldByte/GAINS/Editor/StableDiffusion/StableDiffusionModule.cs:958)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()
```

The webui-user trace is as follows:

```
*** API error: POST: http://127.0.0.1:7860/sdapi/v1/txt2img {'error': 'AssertionError', 'detail': '', 'body': '', 'errors': "Conflict of field 'guidance' and 'guidance_end'"}
    Traceback (most recent call last):
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\anyio\streams\memory.py", line 98, in receive
        return self.receive_nowait()
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\anyio\streams\memory.py", line 93, in receive_nowait
        raise WouldBlock
    anyio.WouldBlock

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\base.py", line 78, in call_next
        message = await recv_stream.receive()
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\anyio\streams\memory.py", line 118, in receive
        raise EndOfStream
    anyio.EndOfStream

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Projects\Python\stable-diffusion-webui\modules\api\api.py", line 186, in exception_handling
        return await call_next(request)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
        response = await self.dispatch_func(request, call_next)
      File "D:\Projects\Python\stable-diffusion-webui\modules\api\api.py", line 150, in log_and_time
        res: Response = await call_next(req)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\base.py", line 84, in call_next
        raise app_exc
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\base.py", line 70, in coro
        await self.app(scope, receive_or_disconnect, send_no_error)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
        await self.app(scope, receive, send)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
        await self.app(scope, receive, send)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
        raise exc
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
        await self.app(scope, receive, sender)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
        raise e
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
        await self.app(scope, receive, send)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\routing.py", line 718, in __call__
        await route.handle(scope, receive, send)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\routing.py", line 276, in handle
        await self.app(scope, receive, send)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\routing.py", line 66, in app
        response = await func(request)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\fastapi\routing.py", line 237, in app
        raw_response = await run_endpoint_function(
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
        return await run_in_threadpool(dependant.call, **values)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
        return await anyio.to_thread.run_sync(func, *args)
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
        return await get_asynclib().run_sync_in_worker_thread(
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
        return await future
      File "D:\anaconda3\envs\stablediffusion\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
        result = context.run(func, *args)
      File "D:\Projects\Python\stable-diffusion-webui\modules\api\api.py", line 482, in text2imgapi
        processed = process_images(p)
      File "D:\Projects\Python\stable-diffusion-webui\modules\processing.py", line 847, in process_images
        res = process_images_inner(p)
      File "D:\Projects\Python\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 56, in processing_process_images_hijack
        cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)
      File "D:\Projects\Python\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 196, in get_cn_batches
        units = external_code.get_all_units_in_processing(p)
      File "D:\Projects\Python\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 133, in get_all_units_in_processing
        return get_all_units(p.scripts, p.script_args)
      File "D:\Projects\Python\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 146, in get_all_units
        return get_all_units_from(script_args[cn_script.args_from : cn_script.args_to])
      File "D:\Projects\Python\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 174, in get_all_units_from
        all_units = [
      File "D:\Projects\Python\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 175, in <listcomp>
        to_processing_unit(script_arg)
      File "D:\Projects\Python\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\external_code.py", line 228, in to_processing_unit
        return ControlNetUnit.from_dict(unit)
      File "D:\Projects\Python\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\args.py", line 423, in from_dict
        values = cls.legacy_field_alias(values)
      File "D:\Projects\Python\stable-diffusion-webui\extensions\sd-webui-controlnet\internal_controlnet\args.py", line 327, in legacy_field_alias
        assert key not in values, f"Conflict of field '{alias}' and '{key}'"
    AssertionError: Conflict of field 'guidance' and 'guidance_end'
```

A1111 Version: 1.10.1
Unity Version: 2022.3.7f1

The dependencies SharpZipLib 1.3.4 and Newtonsoft Json 3.2.1 installed without any problems. ControlNet and Rembg are installed in A1111 and are up to date with the latest version. It's listing the models in A1111 so there's no issue connecting to the running instance on http://127.0.0.1:7860/. I assume the A1111 API has changed and this repo hasn't been updated.

**Comment by AhmadMahmoodRana** [comment]
This might help:This file might fix it
https://bit.ly/4gx42eQ

you may need to install the c compiler

**Comment by AmjedKhaled165** [comment]
download
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by knuthnads** [comment]
Do not click on the links that these spammers posted ^^

**Comment by knuthnads** [comment]
Problem was Gains not being updated to support the latest version of ControlNet.

Solution was to roll back ControlNet to 1.1.411:

git checkout c941954675f0c1a9c8ff6892fe06bfe1c4d588ff
